
Cosmology:
  H0: 67.66
  Omega_m: 0.3111
  PowerSpecFile: 'LCDM_pk0.npz'
  ScaleDepGrowth: False
  GrowthFile: 'LCDM_growth_scale_indep.npz'

Siminfo:
  Boxsize: 500.
  Ngrid: 32

Constraints:
  Fname : 'CF2.npz'
  z_eff: 0.
  Rg: 7.8125
  Sigma_NR: 0.
  WF: True
  RZA: True
  WF_err: False

ICs:
  Seed: 504
  # WNFile: "WN_128.npz"
  z_ic: 30.
  CR: True

Outputs:
  OutputFolder: '32v2'
  Prefix: 'CF2_'
